# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  - TOXENV=flake8
  - TOXENV=py34-django17
  - TOXENV=py34-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django16
  - TOXENV=py26-django17
  - TOXENV=py26-django16

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
