language: python

# Use container based infrastructure
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

env:
  global:
    - secure: lNbb7g6bjHssNvj02PMAhdRMLTje0+WsYRxy7hdoPGJd5uCm3rx5Ha7yYmpv+6hj8SIA6QuE0viKVnife2Eyets99mMuYtsxE+NfHr19HpPEQPUdph3C5q93tupv+vJ52NQnPkb92PNAxDcM4+F+NQrlUBzVhoPjD/8y3whjFmE=
    - secure: PiQisj0TKzfcoSuJe8nCiE3oKz1OT8IW+9lLA73lrHutY/yJrDlGrLoFBp20iIquVOKpGPX1DH1GvHVZeoiiV3qpaF/lJXmmacJte/FrdiVtQ9ezQYtRkY0UGiF+WnqfBPyGBHma9LszGcKHUIg+sXyQ/tIFFhq7U1vMKSPTHJ4=
    - secure: gCi1UP9rgOnfvLT+UNiQkysnXUKvMi5ichNwPNxiXkLYlc66bJLIc/h8YI3V9vV4ICzyMJqEDHXV7T8NP0tsdxdNdEQNvStoaleLz7xsbjW7MZ2XxF13xncG6fksYr/5cjhBbiwg06HTn/VH+TD1FT1u9WUe+0/BJSx1JMnJQgs=
  matrix:
    - DJANGO=1.6 CMD=./test
    - DJANGO=1.7 CMD=./test

matrix:
  # allow_failures:
  exclude:
    # Django 1.7 requires Python 2.7 or later
    - python: 2.6
      env: DJANGO=1.7 CMD=./test
  fast_finish: true
  include:
    - python: 2.7
      env: DJANGO=1.7 CMD="flake8 aldryn_newsblog"

cache:
  directories:
    - $HOME/.wheelhouse

before_install:
  - npm install -g npm

install:
  - pip install coveralls
  - pip wheel --wheel-dir $HOME/.wheelhouse -r test_requirements/django-$DJANGO.txt
  - pip install --use-wheel --no-index --find-links=$HOME/.wheelhouse -r test_requirements/django-$DJANGO.txt

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - python --version
  - coverage erase
  - coverage run test_settings.py
  - coverage report
  - gulp tests:unit
  - gulp tests:lint
  - sh test_requirements/runserver.sh
  - sleep 60
  - gulp tests:integration

after_success: coveralls

after_script:
  - codeclimate < tests/coverage/**/lcov.info

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
