# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  - CMD=./test

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

matrix:
  allow_failures:
    # Python 3.3, 3.4 allowed to fail for now. This is because
    # django-appdata==0.1.3, (latest on GitHub as of this writing) which is a
    # dependency of aldryn-apphooks-config is not really Py3 compatible.
    - python: 3.3
    - python: 3.4
  fast_finish: true
  include:
    - python: 2.7
      env: CMD="flake8 aldryn_faq"

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip wheel --wheel-dir $HOME/.wheelhouse -r test_requirements.txt
  - pip install --use-wheel --no-index --find-links=$HOME/.wheelhouse -r test_requirements.txt

script: coverage run test_settings.py

after_success: coveralls
